name: deploy-vuepress-page
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@v4.2.3
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: main
        FOLDER: docs/.vuepress/dist
        BUILD_SCRIPT: npm install && npm run docs:build
