name: deploy-vuepress-page
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Build
      run: |
        npm install
        npm run docs:build
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4.2.3
      with:
        ssh-key: ${{ secrets.ACCESS_TOKEN }}
        branch: main
        folder: docs/.vuepress/dist
