name: deploy-vuepress-page
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Build
      run: |
        npm install
        npm run docs:build
    - name: Git init
      run: |
        cd  docs/.vuepress/dist
        git config --global user.name johe
        git config --global user.email 634665857@qq.com
        git init 
        git add .
        git commit -m "auto build publish"
    - name: GitHub Push
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.ACCESS_TOKEN }}
        branch: gh-pages
        directory: ./docs/.vuepress/dist
        force: true


