name: deploy-vuepress-page
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Build
      run: |
        npm install
        npm run docs:build
    - name: Deploy
      run: |
        cd  docs/.vuepress/dist
        git config --global user.name johe
        git config --global user.email 634665857@qq.com
        git init 
        git brach -m "gh-pages"
        git add .
        git commit -am "auto build publish"
        git push


